version: "3.8"

services:
  db-user:
    image: postgres:16
    container_name: db-user
    environment:
      POSTGRES_DB: ms-user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - db_user_data:/var/lib/postgresql/data

  db-email:
    image: postgres:16
    container_name: db-email
    environment:
      POSTGRES_DB: ms-email
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5434:5432"
    volumes:
      - db_email_data:/var/lib/postgresql/data

  ms-user:
    image: ms_user:1.0.0
    depends_on:
      - db-user
    ports:
      - "8081:8081"

  ms-email:
    image: ms_email:1.0.0
    depends_on:
      - db-email
    ports:
      - "8082:8082"

  ms-redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  db_user_data:
  db_email_data:
  redis_data: